# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MultiExploding
                                 A QGIS plugin
 This plugin explodes multiparts of all vector files in the selected folder
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-16
        copyright            : (C) 2021 by PrograMapa
        email                : programapa.contacta@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MultiExploding class from file MultiExploding.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Multi_Exploding import MultiExploding
    return MultiExploding(iface)
